# Generated by Django 5.2.6 on 2025-10-16 19:50

import ConferenceApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='desciption',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(30, 'la description doit contenir au moins 30 caractéres')]),
        ),
        migrations.AlterField(
            model_name='conference',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='le titre de la conférence doit contenir uniquement des lettres et espaces (pas de chiffres).', regex='^[a-zA-Z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='keywords',
            field=models.TextField(max_length=255, validators=[ConferenceApp.models.validate_keywords]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='paper',
            field=models.FileField(upload_to='paper/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Seuls les fichiers au format .pdf sont autorisés.')]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
