# Generated by Django 5.2.6 on 2025-10-16 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SessionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='room',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='le nom de la salle ne contient que des lettres et chiffres (pas de caractères spéciaux)', regex='^[a-zA-Z0-9]+$')]),
        ),
    ]
